groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown
        expr: up{job="services"} < 1
        for: 5m
  - name: PaymentGateApiDown1m
    rules:
      - alert: InstanceDown
        expr: up{job="payment-gate"} < 1
        for: 1m
